export function up(knex) {
  return knex.schema
    .createTable('employees', (t) => {
      t.increments('id')
      t.string('name', 255).notNullable()
      t.string('email', 255).notNullable().unique()
      t.string('password_hash', 255).notNullable()
      t.enu('role', ['admin', 'senior_agent', 'agent']).notNullable().defaultTo('agent')
      t.string('department', 255).defaultTo('')
      t.string('avatar', 500).defaultTo('')
      t.string('phone', 50).defaultTo('')
      t.boolean('online').defaultTo(false)
      t.integer('active_tickets').defaultTo(0)
      t.integer('resolved_today').defaultTo(0)
      t.string('title', 100).defaultTo('')
      t.boolean('is_active').defaultTo(true)
      t.timestamp('created_at').defaultTo(knex.fn.now())
    })
    .createTable('tickets', (t) => {
      t.increments('id')
      t.string('title', 500).notNullable()
      t.text('description')
      t.enu('status', ['open', 'in_progress', 'resolved', 'closed']).notNullable().defaultTo('open')
      t.enu('priority', ['low', 'medium', 'high', 'critical']).notNullable().defaultTo('medium')
      t.enu('category', ['bug', 'feature', 'support', 'incident', 'other']).notNullable().defaultTo('support')
      t.integer('created_by').unsigned().notNullable()
      t.integer('assigned_to').unsigned()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.timestamp('updated_at').defaultTo(knex.fn.now())
      t.foreign('assigned_to').references('employees.id').onDelete('SET NULL')
    })
    .createTable('ticket_messages', (t) => {
      t.increments('id')
      t.integer('ticket_id').unsigned().notNullable()
      t.integer('sender_id').unsigned().notNullable()
      t.string('sender_name', 255).notNullable()
      t.string('sender_avatar', 500).defaultTo('')
      t.text('text').notNullable()
      t.json('attachments')
      t.boolean('is_internal').defaultTo(false)
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('ticket_id').references('tickets.id').onDelete('CASCADE')
    })
    .createTable('events', (t) => {
      t.increments('id')
      t.string('title', 200).notNullable()
      t.date('date').notNullable()
      t.string('time', 10)
      t.text('description')
      t.integer('creator_id').unsigned()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('creator_id').references('employees.id').onDelete('SET NULL')
    })
    .createTable('polls', (t) => {
      t.increments('id')
      t.string('title', 200).notNullable()
      t.text('description')
      t.boolean('multiple_choice').defaultTo(false)
      t.integer('created_by').unsigned()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('created_by').references('employees.id').onDelete('SET NULL')
    })
    .createTable('poll_options', (t) => {
      t.increments('id')
      t.integer('poll_id').unsigned().notNullable()
      t.string('text', 200).notNullable()
      t.integer('votes_count').defaultTo(0)
      t.foreign('poll_id').references('polls.id').onDelete('CASCADE')
    })
    .createTable('poll_votes', (t) => {
      t.increments('id')
      t.integer('poll_id').unsigned().notNullable()
      t.integer('option_id').unsigned().notNullable()
      t.integer('user_id').unsigned().notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('poll_id').references('polls.id').onDelete('CASCADE')
      t.foreign('option_id').references('poll_options.id').onDelete('CASCADE')
      t.foreign('user_id').references('employees.id').onDelete('CASCADE')
      t.unique(['poll_id', 'option_id', 'user_id'])
    })
    .createTable('file_folders', (t) => {
      t.increments('id')
      t.string('name', 100).notNullable()
      t.integer('user_id').unsigned().notNullable()
      t.boolean('is_shared').defaultTo(false)
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('user_id').references('employees.id').onDelete('CASCADE')
    })
    .createTable('files', (t) => {
      t.increments('id')
      t.string('name', 200).notNullable()
      t.string('size', 20)
      t.string('type', 50)
      t.integer('folder_id').unsigned()
      t.integer('user_id').unsigned().notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('folder_id').references('file_folders.id').onDelete('CASCADE')
      t.foreign('user_id').references('employees.id').onDelete('CASCADE')
    })
    .createTable('chat_rooms', (t) => {
      t.increments('id')
      t.string('name', 200).notNullable()
      t.enu('type', ['group', 'personal', 'channel']).notNullable().defaultTo('group')
      t.integer('unread').defaultTo(0)
      t.timestamp('created_at').defaultTo(knex.fn.now())
    })
    .createTable('chat_messages', (t) => {
      t.increments('id')
      t.integer('chat_id').unsigned().notNullable()
      t.integer('sender_id').unsigned().notNullable()
      t.string('sender_name', 255).notNullable()
      t.text('text').notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('chat_id').references('chat_rooms.id').onDelete('CASCADE')
    })
    .createTable('wiki_articles', (t) => {
      t.increments('id')
      t.string('title', 300).notNullable()
      t.text('content').notNullable()
      t.string('category', 100).defaultTo('Другое')
      t.json('tags')
      t.integer('author_id').unsigned().notNullable()
      t.string('author_name', 255).notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.timestamp('updated_at').defaultTo(knex.fn.now())
      t.foreign('author_id').references('employees.id').onDelete('CASCADE')
    })
    .createTable('news_posts', (t) => {
      t.increments('id')
      t.string('title', 300).notNullable()
      t.text('content').notNullable()
      t.boolean('important').defaultTo(false)
      t.integer('author_id').unsigned().notNullable()
      t.string('author_name', 255).notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('author_id').references('employees.id').onDelete('CASCADE')
    })
    .createTable('push_subscriptions', (t) => {
      t.increments('id')
      t.integer('user_id').unsigned().notNullable()
      t.text('subscription_json').notNullable()
      t.timestamp('created_at').defaultTo(knex.fn.now())
      t.foreign('user_id').references('employees.id').onDelete('CASCADE')
      t.unique('user_id')
    })
}

export function down(knex) {
  return knex.schema
    .dropTableIfExists('push_subscriptions')
    .dropTableIfExists('news_posts')
    .dropTableIfExists('wiki_articles')
    .dropTableIfExists('chat_messages')
    .dropTableIfExists('chat_rooms')
    .dropTableIfExists('files')
    .dropTableIfExists('file_folders')
    .dropTableIfExists('poll_votes')
    .dropTableIfExists('poll_options')
    .dropTableIfExists('polls')
    .dropTableIfExists('events')
    .dropTableIfExists('ticket_messages')
    .dropTableIfExists('tickets')
    .dropTableIfExists('employees')
}
